// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zknxiuhgkpjeapnkejrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbnhpdWhna3BqZWFwbmtlanJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Njk2ODgsImV4cCI6MjA1OTE0NTY4OH0.TBWVXVA8emp1mlZCYNbglyf4omt5Ea2L3E5blpRyMxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);